server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "1"
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: false

kafka:
  topic:
    order-events: order-events

